### ISSUE TITLE
Update of Ionic alert, popover and modal

### ISSUE THREAD

**Issue by adoultremont** [DAB0mB/ionic2-meteor-messenger#5]
Hi,

Thanks for this tutorial. Very cool.

I have encountered a few issues to get until the end. I am not familiar with PR but I share them here this might help someone.

It seems that in the latest Ionic beta, Alert, Modal and Popover have been replaced by AlertController, ModalController and PopoverController, see

[Ionic v2 Docs](http://ionicframework.com/docs/v2/api/components/alert/AlertController/)

Cheers,

Alexis

**Comment by dotansimha** [comment]
Done
