### ISSUE TITLE
Dependency conflicts between meteor-client-side & accounts-base-client-side

### ISSUE THREAD

**Issue by adoultremont** [DAB0mB/ionic2-meteor-messenger#6]
Hello,

I encountered this dependency problem while following the tutorial:

npm does not satisfy its siblings' peerDependencies requirements

npm install meteor-client-side --save installs the version 1.3.4 of meteor-client-side

npm install accounts-base-client-side and npm install accounts-phone (the NPM version) requires the version 
`"meteor-client-side": "~0.2.3"`

I solved it by downloading a local copy of these packages and changed the dependency to 1.3.4 in bower.json.

It would be great to update them to the latest version.

Thanks,

Alexis

**Comment by AddoSolutions** [comment]
I believe I have the same issue:

```
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package meteor-client-side@1.3.4 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer accounts-phone@0.0.1 wants meteor-client-side@~0.2.3
```

**Comment by dotansimha** [comment]
@idanwe 

As a workaround, you can use latest Node, which does not throws an error in case of peer issues
