### ISSUE TITLE
ionic serve --> meteor run

### ISSUE THREAD

**Issue by steff1193** [DAB0mB/ionic2-meteor-messenger#9]
step-1.md says to use "ionic server" to run the application. That is good, since this is a "Ionic CLI" based project/tutorial. But then suddenly step-5.md says to use "meteor run --settings settings.json". Guess this is to give the right settings.json to meteor, but cant you do that using "ionic serve"? If yes, I guess the step-5.md should tell about it.
I have tried with "meteor run --settings settings.json", but it does not work for me (I cd to api folder first). The application never starts. It says "Downloading meteor-tool@1.3.4_3" and download seems to progress, but when the progress-bar reaches the end, it just continues saying "Downloading meteor-tool@1.3.4_3" and nothing ever happens after that.

**Comment by steff1193** [comment]
I succeeded starting the application with "meteor run --settings settings.json" from the api folder. But, unlike when I use "ionic serve" and go to http://localhost:8100, I just get a blank page when going to http://localhost:3000.

Page source:
<!DOCTYPE html>
<html>
<head>



</head>
<body>



<script type="text/javascript">__meteor_runtime_config__ = JSON.parse(decodeURIComponent("%7B%22meteorRelease%22%3A%22METEOR%401.3.4.3%22%2C%22meteorEnv%22%3A%7B%22NODE_ENV%22%3A%22development%22%2C%22TEST_METADATA%22%3A%22%7B%7D%22%7D%2C%22PUBLIC_SETTINGS%22%3A%7B%7D%2C%22ROOT_URL%22%3A%22http%3A%2F%2Flocalhost%3A3000%2F%22%2C%22ROOT_URL_PATH_PREFIX%22%3A%22%22%2C%22appId%22%3A%221uoizbn1nxjhyw15tgshd%22%2C%22autoupdateVersion%22%3A%22d06dc35b06f7c82cb43ffc428cf865d8d2304fd7%22%2C%22autoupdateVersionRefreshable%22%3A%22cf4fc61b611d7bc8e6af2f288d9e4aa6d806195c%22%2C%22autoupdateVersionCordova%22%3A%22none%22%7D"));</script>

  <script type="text/javascript" src="/packages/underscore.js?hash=27b3d669b418de8577518760446467e6ff429b1e"></script>
  <script type="text/javascript" src="/packages/meteor.js?hash=ae8b8affa9680bf9720bd8f7fa112f13a62f71c3"></script>
  <script type="text/javascript" src="/packages/meteor-base.js?hash=78d760bd25caaa0aaaa51b630ff14fdbfddf0a80"></script>
  <script type="text/javascript" src="/packages/mobile-experience.js?hash=228175c74a6bdd2cc7d213d791ad7633cde48eb6"></script>
  <script type="text/javascript" src="/packages/modules-runtime.js?hash=b7370236eeaf57e8f4ac703424bc831028392451"></script>
  <script type="text/javascript" src="/packages/modules.js?hash=b75580019c1f5383e7ac6ef78cc37873c7099973"></script>
  <script type="text/javascript" src="/packages/es5-shim.js?hash=e4d68c9ebbcdbd230d16f4bd933ee8dbf2978a22"></script>
  <script type="text/javascript" src="/packages/promise.js?hash=2d5b025794b9c9e54e5cf6bea71c642ef921a2ed"></script>
  <script type="text/javascript" src="/packages/ecmascript-runtime.js?hash=e4dd2b138377d446dc7dc3af21bb5bcd4b2b88a3"></script>
  <script type="text/javascript" src="/packages/babel-compiler.js?hash=aa1ba23957a2a38a24bad15d8eb7dda850adb69a"></script>
  <script type="text/javascript" src="/packages/ecmascript.js?hash=66523b499a44a9bde66a5c90da84c2f620fa9038"></script>
  <script type="text/javascript" src="/packages/base64.js?hash=e5bbbab7ff79348492ae7e574cf7931e2ee72a11"></script>
  <script type="text/javascript" src="/packages/ejson.js?hash=b1036d3e150ea4ea6470ea9cd45a48a12835d57e"></script>
  <script type="text/javascript" src="/packages/id-map.js?hash=e665ae78e62a315f5fd218a68e373e364f74136c"></script>
  <script type="text/javascript" src="/packages/ordered-dict.js?hash=61f1d7f16d10d9f37890aaf2455697ef7c8c378b"></script>
  <script type="text/javascript" src="/packages/tracker.js?hash=b605200c15f3a57abb701c7cbc58ca5b0f2802d7"></script>
  <script type="text/javascript" src="/packages/babel-runtime.js?hash=543034092ecef720d1732d8f72ab489f1877696f"></script>
  <script type="text/javascript" src="/packages/random.js?hash=c4879267bde8bbc5ba66d23fa420cb239c44fb68"></script>
  <script type="text/javascript" src="/packages/mongo-id.js?hash=172813d0ff26d0175642f30557d9980b3d852a17"></script>
  <script type="text/javascript" src="/packages/diff-sequence.js?hash=21ebcc9500dc0ea4d28ec4454f001dfed0c5ab26"></script>
  <script type="text/javascript" src="/packages/geojson-utils.js?hash=7214728d388f610508afa2a208b6117470822707"></script>
  <script type="text/javascript" src="/packages/minimongo.js?hash=88217d643bc16fdf3505c6d4b2b8f5ddc400c49a"></script>
  <script type="text/javascript" src="/packages/check.js?hash=bf95dee84c2be9008274d2385c637659760b9057"></script>
  <script type="text/javascript" src="/packages/retry.js?hash=91c22616ae67cee99080f81fae9e6083bf7c5711"></script>
  <script type="text/javascript" src="/packages/ddp-common.js?hash=a99cb35fd21daff658b592895ec8e2da5ee4c434"></script>
  <script type="text/javascript" src="/packages/reload.js?hash=ad99c3e418c3fdc4fd1e08796369bded98b26b3d"></script>
  <script type="text/javascript" src="/packages/ddp-client.js?hash=27502404fad7fc072e57e8b0b6719f40d92709c7"></script>
  <script type="text/javascript" src="/packages/ddp.js?hash=752b775e282ca59c21ca09b9cc61f5fffb9ea2a1"></script>
  <script type="text/javascript" src="/packages/ddp-server.js?hash=f22a106538ade54bd1190c4d309f2f94bdd3ec9b"></script>
  <script type="text/javascript" src="/packages/allow-deny.js?hash=11ff6d1a797cb3d6608a96e8ab0bd82a4947ff49"></script>
  <script type="text/javascript" src="/packages/mongo.js?hash=f257f65490c0d34a164a6d8801ede96905340462"></script>
  <script type="text/javascript" src="/packages/blaze-html-templates.js?hash=789c063ee96f7c7159040c8b3bf86cbc4ede975f"></script>
  <script type="text/javascript" src="/packages/reactive-var.js?hash=4ec04bee8ba46a9256d34c18c7f0fbbb6e782570"></script>
  <script type="text/javascript" src="/packages/jquery.js?hash=22a0055f59bd150c435c5aba34c7c59076b8bcd9"></script>
  <script type="text/javascript" src="/packages/standard-minifier-css.js?hash=28195a94bf7be7891ced328ed580307f7ac6ed54"></script>
  <script type="text/javascript" src="/packages/standard-minifier-js.js?hash=555d6f310158f363207df43e0353de4a4883d7af"></script>
  <script type="text/javascript" src="/packages/ddp-rate-limiter.js?hash=af60434f2a5f818b825b7a15c155f7afd5ac47ec"></script>
  <script type="text/javascript" src="/packages/localstorage.js?hash=0b3ae3298494da2289abab2377342a1054cfca0b"></script>
  <script type="text/javascript" src="/packages/callback-hook.js?hash=fff7fdef0707c85900b21f766a4b6c65bf278ff4"></script>
  <script type="text/javascript" src="/packages/deps.js?hash=af038305759a654448f8031d60f379835ae67a8c"></script>
  <script type="text/javascript" src="/packages/htmljs.js?hash=3035d42f05f842d4beb2111cc6739b9ce6cd4ca4"></script>
  <script type="text/javascript" src="/packages/observe-sequence.js?hash=550c39b36ab0e65194ea03cdc7ecbe99dcdd07f6"></script>
  <script type="text/javascript" src="/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea"></script>
  <script type="text/javascript" src="/packages/accounts-base.js?hash=3f6353a90da402397ef0b889e3812a40c0a71704"></script>
  <script type="text/javascript" src="/packages/sha.js?hash=569709b873cd1ba2cef4f2b0732cb4923ff5ce20"></script>
  <script type="text/javascript" src="/packages/srp.js?hash=94d5df94b266ef008d0425c828f1715512e429ef"></script>
  <script type="text/javascript" src="/packages/okland_accounts-phone.js?hash=71f2067ead588c3a5550c6787257da2a788dc273"></script>
  <script type="text/javascript" src="/packages/reywood_publish-composite.js?hash=a8f970faef398b013405e6408ef39a2e8d8a8ad5"></script>
  <script type="text/javascript" src="/packages/meteortypescript_compiler.js?hash=dde070e158419fad46e4794db5e8a51f30a07bb7"></script>
  <script type="text/javascript" src="/packages/webapp.js?hash=b74e2292d6087dc6f77d86b7e71ac0d672b0fbe8"></script>
  <script type="text/javascript" src="/packages/livedata.js?hash=e7fb2e783bc81b00b914c2e27966b7b6d3d081b6"></script>
  <script type="text/javascript" src="/packages/hot-code-push.js?hash=9121bd39124b5010787be320ca559344b6691712"></script>
  <script type="text/javascript" src="/packages/spacebars.js?hash=65db8b6a8e3fca189b416de702967b1cb83d57d5"></script>
  <script type="text/javascript" src="/packages/templating.js?hash=f43427e80c4a8a93daf5ed094c8141a0ee19c804"></script>
  <script type="text/javascript" src="/packages/launch-screen.js?hash=bc0fd472cf89d0c9b8146f07ba048efcc11ef9ee"></script>
  <script type="text/javascript" src="/packages/ui.js?hash=d0665bbf032532e2284f8843b30500babb10dd4d"></script>
  <script type="text/javascript" src="/packages/barbatus_typescript-compiler.js?hash=eac49e0256055150c2f7a012c24cc71db50b6836"></script>
  <script type="text/javascript" src="/packages/barbatus_typescript.js?hash=484a4656e076f96c1bf044b151650f7ce11c6adc"></script>
  <script type="text/javascript" src="/packages/autoupdate.js?hash=cd7c85bd6e2795c4352bc0a76604e45642e47c31"></script>
  <script type="text/javascript" src="/packages/barbatus_typescript-runtime.js?hash=2d2e1608712f5b63617143ff333b9cdfd927835d"></script>
  <script type="text/javascript" src="/packages/global-imports.js?hash=2619f3bc693f346332cabf20d8bb73d7e668cff5"></script>
  <script type="text/javascript" src="/app/app.js?hash=da39a3ee5e6b4b0d3255bfef95601890afd80709"></script>
  <script type="text/javascript" src="/packages/service-configuration.js?hash=331fe144dc8f69e5e44f23dd74b9de74ed80c6f3"></script>


</body>
</html>

**Comment by steff1193** [comment]
Ahhh, ok I belive I figured it out. You have to run both "meteor run" and "ionic server". I thought meteor would also serve the ionic stuff and/or that ionic would run a meteor. But I guess not?
The tutorial should probably state, for dummies like me, that you have to run both - probably already in step-3.md?

**Comment by dotansimha** [comment]
Please try the latest version, we fixed a lot of issues.
